# B4.5: PDF Integration - Export Functionality

from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.linecharts import HorizontalLineChart
from reportlab.graphics.charts.barcharts import VerticalBarChart
import io
from typing import Dict, Any
import base64

class PDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom PDF styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor('#1f2937')
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=12,
            textColor=colors.HexColor('#374151')
        ))
        
        self.styles.add(ParagraphStyle(
            name='MetricValue',
            parent=self.styles['Normal'],
            fontSize=14,
            textColor=colors.HexColor('#059669'),
            alignment=1  # Center alignment
        ))
    
    async def generate_report_pdf(self, report_data: Dict[str, Any]) -> bytes:
        """Generate complete PDF report"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72,
                              topMargin=72, bottomMargin=18)
        
        story = []
        
        # Title page
        story.extend(self._create_title_page(report_data))
        story.append(PageBreak())
        
        # Executive summary
        story.extend(self._create_executive_summary(report_data['sections']['executive_summary']))
        story.append(PageBreak())
        
        # Financial analysis
        story.extend(self._create_financial_analysis(report_data['sections']['financial_analysis']))
        story.append(PageBreak())
        
        # Valuation analysis
        story.extend(self._create_valuation_analysis(report_data['sections']['valuation']))
        story.append(PageBreak())
        
        # Risk assessment
        story.extend(self._create_risk_assessment(report_data['sections']['risk_assessment']))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
    
    def _create_title_page(self, report_data: Dict[str, Any]) -> list:
        """Create PDF title page"""
        story = []
        
        # Company name and ticker
        title = f"{report_data['company_name']} ({report_data['ticker']})"
        story.append(Paragraph(title, self.styles['CustomTitle']))
        story.append(Spacer(1, 0.5*inch))
        
        # Report metadata
        meta_data = [
            ['Report Type:', 'Comprehensive Stock Analysis'],
            ['Generated:', report_data['created_at'][:10]],
            ['Pages:', str(report_data['page_count'])],
            ['Rating:', report_data['rating']],
            ['Price Target:', f"${report_data['sections']['executive_summary']['price_target']}"]
        ]
        
        meta_table = Table(meta_data, colWidths=[2*inch, 3*inch])
        meta_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        
        story.append(meta_table)
        story.append(Spacer(1, 1*inch))
        
        # Disclaimer
        disclaimer = """
        This report is generated by MarketMind Pro AI analysis and is for informational purposes only. 
        It should not be considered as investment advice. Please consult with a qualified financial 
        advisor before making investment decisions.
        """
        story.append(Paragraph(disclaimer, self.styles['Normal']))
        
        return story
    
    def _create_executive_summary(self, summary_data: Dict[str, Any]) -> list:
        """Create executive summary section"""
        story = []
        
        story.append(Paragraph("Executive Summary", self.styles['SectionHeader']))
        
        # Key metrics table
        metrics_data = [
            ['Metric', 'Value'],
            ['Price Target', f"${summary_data['price_target']}"],
            ['Current Price', f"${summary_data.get('current_price', 'N/A')}"],
            ['Upside Potential', f"{summary_data['upside']}%"],
            ['Rating', summary_data['rating']]
        ]
        
        metrics_table = Table(metrics_data, colWidths=[2.5*inch, 2*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(metrics_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Investment thesis
        story.append(Paragraph("Investment Thesis", self.styles['Heading3']))
        story.append(Paragraph(summary_data['thesis'], self.styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
        
        # Bull/Bear points
        if summary_data.get('bull_points'):
            story.append(Paragraph("Key Positives", self.styles['Heading4']))
            for point in summary_data['bull_points']:
                story.append(Paragraph(f"• {point}", self.styles['Normal']))
            story.append(Spacer(1, 0.1*inch))
        
        if summary_data.get('bear_points'):
            story.append(Paragraph("Key Risks", self.styles['Heading4']))
            for point in summary_data['bear_points']:
                story.append(Paragraph(f"• {point}", self.styles['Normal']))
        
        return story
    
    def _create_financial_analysis(self, financial_data: Dict[str, Any]) -> list:
        """Create financial analysis section"""
        story = []
        
        story.append(Paragraph("Financial Analysis", self.styles['SectionHeader']))
        
        # Revenue table
        if financial_data.get('income_statement'):
            story.append(Paragraph("Income Statement (in millions)", self.styles['Heading3']))
            
            income_data = [['Metric'] + list(financial_data['income_statement'].keys())]
            for metric, values in financial_data['income_statement'].items():
                if isinstance(values, dict):
                    row = [metric] + [str(v) for v in values.values()]
                    income_data.append(row)
            
            income_table = Table(income_data)
            income_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(income_table)
            story.append(Spacer(1, 0.3*inch))
        
        return story
    
    def _create_valuation_analysis(self, valuation_data: Dict[str, Any]) -> list:
        """Create valuation analysis section"""
        story = []
        
        story.append(Paragraph("Valuation Analysis", self.styles['SectionHeader']))
        
        # DCF summary
        if valuation_data.get('dcf_valuation'):
            story.append(Paragraph("Discounted Cash Flow Analysis", self.styles['Heading3']))
            
            dcf_data = [
                ['DCF Fair Value', f"${valuation_data['dcf_valuation'].get('fair_value', 'N/A')}"],
                ['Discount Rate', f"{valuation_data['dcf_valuation'].get('discount_rate', 'N/A')}%"],
                ['Terminal Growth', f"{valuation_data['dcf_valuation'].get('terminal_growth', 'N/A')}%"],
                ['NPV', f"${valuation_data['dcf_valuation'].get('npv', 'N/A')}M"]
            ]
            
            dcf_table = Table(dcf_data, colWidths=[2*inch, 2*inch])
            dcf_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ]))
            
            story.append(dcf_table)
        
        return story
    
    def _create_risk_assessment(self, risk_data: Dict[str, Any]) -> list:
        """Create risk assessment section"""
        story = []
        
        story.append(Paragraph("Risk Assessment", self.styles['SectionHeader']))
        
        if risk_data.get('key_risks'):
            story.append(Paragraph("Key Investment Risks", self.styles['Heading3']))
            
            for i, risk in enumerate(risk_data['key_risks'], 1):
                story.append(Paragraph(f"{i}. {risk}", self.styles['Normal']))
                story.append(Spacer(1, 0.1*inch))
        
        return story

# FastAPI endpoint for PDF generation
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

router = APIRouter()

@router.get("/reports/{report_id}/pdf")
async def export_report_pdf(report_id: str):
    """Export report as PDF"""
    try:
        # Fetch report data
        from app.services.report_service import ReportService
        report_service = ReportService()
        report_data = await report_service.get_report(report_id)
        
        if not report_data:
            raise HTTPException(status_code=404, detail="Report not found")
        
        # Generate PDF
        pdf_generator = PDFGenerator()
        pdf_bytes = await pdf_generator.generate_report_pdf(report_data)
        
        # Return PDF response
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f"attachment; filename={report_data['ticker']}_report.pdf"
            }
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(e)}")