#!/usr/bin/env python3
"""
Ultra-Systematic PDF Generator
Professional institutional-quality PDF generation with proper styling
"""

import os
import tempfile
from typing import Dict, Any
from weasyprint import HTML, CSS
from ultra_formatter import ReportFormatter

class UltraPDFGenerator:
    """
    Ultra-systematic PDF generator with professional institutional styling
    """
    
    def __init__(self):
        self.formatter = ReportFormatter()
        self.pdf_styles = self._get_pdf_styles()
    
    def generate_pdf(self, report_data: Dict[str, Any], output_path: str) -> str:
        """
        Generate professional PDF from report data
        """
        
        # Step 1: Format the report data
        formatted_report = self.formatter.process_report_json(report_data)
        
        # Step 2: Create complete HTML document
        html_document = self._create_html_document(formatted_report, report_data)
        
        # Step 3: Generate PDF with WeasyPrint
        pdf_path = self._generate_pdf_file(html_document, output_path)
        
        return pdf_path
    
    def _create_html_document(self, formatted_report: Dict[str, Any], original_data: Dict[str, Any]) -> str:
        """Create complete HTML document for PDF generation"""
        
        # Get the formatted HTML content
        html_content = formatted_report['html_content']
        
        # Create complete HTML document
        html_document = f'''
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{original_data.get('symbol', 'Stock')} - Investment Analysis Report</title>
            <style>
                {self.pdf_styles}
            </style>
        </head>
        <body>
            <div class="pdf-document">
                <div class="pdf-header">
                    <h1 class="pdf-title">MarketMind Pro</h1>
                    <h2 class="pdf-subtitle">{original_data.get('symbol', 'Stock')} - Institutional Investment Analysis</h2>
                    <div class="pdf-meta">
                        <p>Generated: {formatted_report['metadata']['formatted_at'][:10]}</p>
                        <p>Professional Equity Research Report</p>
                    </div>
                </div>
                
                <div class="pdf-body">
                    {html_content}
                </div>
                
                <div class="pdf-footer">
                    <p>This report is generated by MarketMind Pro for institutional investment research purposes.</p>
                    <p>Past performance does not guarantee future results. All investments carry risk of loss.</p>
                </div>
            </div>
        </body>
        </html>
        '''
        
        return html_document
    
    def _generate_pdf_file(self, html_document: str, output_path: str) -> str:
        """Generate PDF file using WeasyPrint"""
        
        try:
            # Create temporary HTML file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False, encoding='utf-8') as temp_html:
                temp_html.write(html_document)
                temp_html_path = temp_html.name
            
            # Generate PDF
            HTML(filename=temp_html_path).write_pdf(output_path)
            
            # Clean up temporary file
            os.unlink(temp_html_path)
            
            print(f"✅ Ultra-PDF generated: {output_path}")
            return output_path
            
        except Exception as e:
            print(f"❌ PDF generation failed: {str(e)}")
            raise
    
    def _get_pdf_styles(self) -> str:
        """Get comprehensive PDF styles"""
        return '''
        @page {
            size: A4;
            margin: 1in;
            @top-center {
                content: "MarketMind Pro - Institutional Research";
                font-size: 10pt;
                color: #666;
            }
            @bottom-center {
                content: "Page " counter(page) " of " counter(pages);
                font-size: 10pt;
                color: #666;
            }
        }
        
        .pdf-document {
            font-family: 'Times New Roman', serif;
            font-size: 11pt;
            line-height: 1.4;
            color: #1a1a1a;
        }
        
        .pdf-header {
            text-align: center;
            margin-bottom: 30pt;
            border-bottom: 2pt solid #2563eb;
            padding-bottom: 20pt;
        }
        
        .pdf-title {
            font-size: 24pt;
            font-weight: bold;
            color: #2563eb;
            margin-bottom: 10pt;
        }
        
        .pdf-subtitle {
            font-size: 18pt;
            font-weight: bold;
            color: #1a1a1a;
            margin-bottom: 15pt;
        }
        
        .pdf-meta {
            font-size: 10pt;
            color: #666;
        }
        
        .pdf-body {
            margin: 20pt 0;
        }
        
        .report-container {
            /* Override for PDF */
            max-width: none;
            margin: 0;
            padding: 0;
        }
        
        .section-title {
            font-size: 16pt;
            font-weight: bold;
            color: #1a1a1a;
            margin: 25pt 0 15pt 0;
            border-bottom: 1pt solid #2563eb;
            padding-bottom: 5pt;
            page-break-after: avoid;
        }
        
        .report-h2 {
            font-size: 14pt;
            font-weight: bold;
            color: #1a1a1a;
            margin: 20pt 0 10pt 0;
            page-break-after: avoid;
        }
        
        .report-h3 {
            font-size: 12pt;
            font-weight: bold;
            color: #1a1a1a;
            margin: 15pt 0 8pt 0;
            page-break-after: avoid;
        }
        
        .report-paragraph {
            font-size: 11pt;
            color: #1a1a1a;
            margin-bottom: 12pt;
            line-height: 1.4;
            text-align: justify;
        }
        
        .report-bold {
            font-weight: bold;
            color: #1a1a1a;
        }
        
        .rating-badge {
            display: inline-block;
            padding: 3pt 8pt;
            border-radius: 10pt;
            font-weight: bold;
            font-size: 10pt;
            margin: 0 2pt;
        }
        
        .rating-BUY {
            background-color: #10b981;
            color: white;
        }
        
        .rating-HOLD {
            background-color: #f59e0b;
            color: white;
        }
        
        .rating-SELL {
            background-color: #ef4444;
            color: white;
        }
        
        .price-target {
            font-weight: bold;
            color: #2563eb;
        }
        
        .percentage {
            font-weight: bold;
            color: #059669;
        }
        
        .currency {
            font-weight: bold;
            color: #059669;
        }
        
        .report-list {
            margin: 12pt 0;
            padding-left: 15pt;
        }
        
        .report-bullet {
            margin-bottom: 6pt;
            color: #1a1a1a;
        }
        
        .pdf-footer {
            margin-top: 30pt;
            padding-top: 15pt;
            border-top: 1pt solid #ccc;
            font-size: 9pt;
            color: #666;
            text-align: center;
        }
        
        /* Page break controls */
        .report-section {
            page-break-inside: avoid;
            margin-bottom: 20pt;
        }
        
        .section-content {
            orphans: 3;
            widows: 3;
        }
        
        /* Print optimizations */
        h1, h2, h3, h4, h5, h6 {
            page-break-after: avoid;
        }
        
        p {
            orphans: 2;
            widows: 2;
        }
        '''

# Test the ultra PDF generator
if __name__ == "__main__":
    generator = UltraPDFGenerator()
    
    # Test data
    test_data = {
        'symbol': 'MSFT',
        'sections': {
            'executive_summary': {
                'title': 'Executive Summary',
                'content': '''## Investment Recommendation: **BUY**

Price Target: $420.00 | Current Price: $380.50 | Upside Potential: 10.4%

### Key Investment Thesis
Microsoft represents a compelling investment opportunity driven by:

- **Cloud Leadership**: Azure growing 30%+ annually
- **AI Integration**: Copilot driving productivity gains  
- **Subscription Model**: Recurring revenue stability

Rating: BUY with 12-month target of $420.00

### Financial Highlights
- Revenue: $245.1B (+16% YoY)
- Operating Margin: 42.0% (industry-leading)
- Free Cash Flow: $65.2B (+18% YoY)
- Cloud Revenue: $87.9B (+24% YoY)'''
            }
        }
    }
    
    print("🧪 Testing Ultra-PDF Generator...")
    pdf_path = generator.generate_pdf(test_data, "Ultra_Test_Report.pdf")
    
    # Check file size
    if os.path.exists(pdf_path):
        size = os.path.getsize(pdf_path)
        print(f"📄 PDF size: {size:,} bytes")
        print(f"✅ Ultra-PDF generation successful!")
    else:
        print("❌ PDF generation failed!")
